-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 14:38:47 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema veladb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema veladb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `veladb` DEFAULT CHARACTER SET utf8 ;
USE `veladb` ;

-- -----------------------------------------------------
-- Table `veladb`.`RoleUtilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`RoleUtilisateur` (
  `idRoleUtilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoleUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`EtatUtilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`EtatUtilisateur` (
  `idEtatUtilisateur` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEtatUtilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`Utilisateur` (
  `idUtilisateur` INT NOT NULL,
  `Mail` VARCHAR(45) NULL,
  `MotDePasse` VARCHAR(45) NULL,
  `Nom` VARCHAR(45) NULL,
  `idRole` INT NULL,
  `idEtat` INT NULL,
  `idParrain` INT NULL,
  PRIMARY KEY (`idUtilisateur`),
  INDEX `IDRole_idx` (`idRole` ASC) VISIBLE,
  INDEX `IDEtat_idx` (`idEtat` ASC) VISIBLE,
  INDEX `IDParrain_idx` (`idParrain` ASC) VISIBLE,
  CONSTRAINT `IDRole`
    FOREIGN KEY (`idRole`)
    REFERENCES `veladb`.`RoleUtilisateur` (`idRoleUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDEtat`
    FOREIGN KEY (`idEtat`)
    REFERENCES `veladb`.`EtatUtilisateur` (`idEtatUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IDParrain`
    FOREIGN KEY (`idParrain`)
    REFERENCES `veladb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`RoleEmploi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`RoleEmploi` (
  `idRoleEmploi` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idRoleEmploi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`EtatRestaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`EtatRestaurant` (
  `idEtatRestaurant` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEtatRestaurant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`Restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`Restaurant` (
  `idRestaurant` INT NOT NULL,
  `Nom` VARCHAR(45) NULL,
  `idEtat` INT NULL,
  PRIMARY KEY (`idRestaurant`),
  INDEX `idEtatRestaurant_idx` (`idEtat` ASC) VISIBLE,
  CONSTRAINT `idEtatRestaurant`
    FOREIGN KEY (`idEtat`)
    REFERENCES `veladb`.`EtatRestaurant` (`idEtatRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `veladb`.`Emploi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`Emploi` (
  `idRestaurant` INT NULL,
  `idUtilisateur` INT NULL,
  `idRoleEmploi` INT NULL,
  INDEX `idResto_idx` (`idRestaurant` ASC) VISIBLE,
  INDEX `idUtilisateur_idx` (`idUtilisateur` ASC) VISIBLE,
  INDEX `idRoleEmploi_idx` (`idRoleEmploi` ASC) VISIBLE,
  CONSTRAINT `idResto`
    FOREIGN KEY (`idRestaurant`)
    REFERENCES `veladb`.`Restaurant` (`idRestaurant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilisateur`
    FOREIGN KEY (`idUtilisateur`)
    REFERENCES `veladb`.`Utilisateur` (`idUtilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idRoleEmploi`
    FOREIGN KEY (`idRoleEmploi`)
    REFERENCES `veladb`.`RoleEmploi` (`idRoleEmploi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `veladb` ;

-- -----------------------------------------------------
-- Placeholder table for view `veladb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veladb`.`view1` (`idRestaurant` INT, `Nom` INT, `idEtat` INT, `idRoleEmploi` INT, `idRoleUtilisateur` INT);

-- -----------------------------------------------------
-- View `veladb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `veladb`.`view1`;
USE `veladb`;
CREATE  OR REPLACE VIEW `view1` AS SELECT * FROM Restaurant,RoleEmploi,RoleUtilisateur;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

